/*
MagicTypeStruct:
	<SkillID>
	<ActionSort>
	<SkillName[16]>
	<IsOffensiveOnUse>
	<IsGroundTargeted>
	<IsMultiTarget>
	<TargetFlag:000Body|Passive|Terrain|None|Self>
	<SkillLevel>
	<MPCost>
	<Power>
	<IntoneEffectDuration>
	<Accuracy>
	<Time?>
	<Range?>
	<MaxDistance>
	<Status?>
	<JobRequired>
	<XPRequired>
	<LevelRequired>
	<SkillType:0=Magic,1=XPSkill,2=Martial>
	<WeaponRequired: 3 first digits of ItemID>
	<ActiveTime?>
	<IsAutoActive:4=WeaponPassiveSkill.0=None>
	<FloorAttribute?>
	<IsAutoLearned>
	<AutoLearnLevel>
	<DropWeapon?>
	<StaminaCost>
	<HitsWithWeapon>
	<UsesItem?>
	<NextSkillIDAutoCast>
	<UseDelay>
	<UseItemNum?>
	<SenderAction?>
	<ShortDescription[64]>
	<Description[256]>
	<IntoneEffect[64]>
	<IntoneSFX[260]>
	<SenderEffect[64]>
	<SenderSFX[260]>
	<TargetDelay?>
	<TargetEffect[64]>
	<TargetSFX[260>
	<GroundEffect[64]>
	<TraceEffect[64]>
	<ScreenRepresent?>
	<IsUsableInMarket>
	<IsStaggering>
*/